#!/bin/sh
cd /root/agri-vision
xset s noblank & # don't blank the video device
xset s off & # don't activate screensaver
xset -dpms &
xset dpms force on # disable DPMS (Energy Star) features.
python agrivision.py
